MyWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from MyWeb import settings
from MyWeb.APScheduler import start_scheduler

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('login/', include('login.urls')),
    path('autotest/', include('autotest.urls', namespace='autotest')),
    path('sysadmin/', include('SysAdmin.urls', namespace='sysadmin')),
    path('apitest/', include('ApiTest.urls', namespace='apitest')),
    path('datapanel/', include('DataPanel.urls', namespace='datapanel')),
]

# 随项目启动运行
if settings.APSCHEDULER == 'on':
    start_scheduler()

autotest/urls.py
from django.urls import path
from . import views

app_name = 'autotest'
urlpatterns = [
    path('run_his/', views.RunHisV.as_view(), name='run_his'),
    path('run_his/get/', views.get_run_his, name='get_his'),
    path('run_his/report/', views.get_report, name='report'),
    path('run_his/comment/', views.update_runhis_comment, name='update_runhis_comment'),
    path('execution/', views.ExecutionV.as_view(), name='execution'),
    path('jobs/get/', views.get_jobs, name='get_jobs'),
    path('job/exec/', views.exec_job, name='exec_job'),
    path('job/new_layer/', views.new_job_html, name='new_job_html'),
    path('job/save/', views.save_new_job, name='save_new_job'),
    path('job/del/', views.del_job, name='del_job'),
    path('node/register/', views.regsiter_node, name='register_node'),
    path('suite/count/', views.update_suite_cases_count, name='update_suite_case_count'),
    path('datasource/update/', views.update_ds, name='update_ds'),
    path('datasource/', views.DataSourceV.as_view(), name='datasource'),
    path('datasource/get/', views.get_ds, name='get_ds'),
    path('datasource/download/', views.download_ds, name='download_ds'),
    path('datasource/preview/', views.DataSourcePreviewV.as_view(), name='ds_preview'),
]

autotest/models.py
from django.db import models
from MyWeb import settings
# Create your models here.


class RunHis(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    group = models.CharField(max_length=64, null=False)
    suite = models.CharField(max_length=64, null=False)
    case = models.CharField(max_length=128, null=False)
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=200, null=True)
    tester = models.CharField(max_length=32)
    comment = models.CharField(max_length=200, null=True)
    report = models.CharField(max_length=200)
    result = models.CharField(max_length=1)
    create_time = models.DateTimeField(auto_created=False)
    update_time = models.DateTimeField(auto_created=False)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'run_his'


class ResDict(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    result = models.CharField(max_length=1, null=False)
    description = models.CharField(max_length=32, null=False)

    def __str__(self):
        return self.description

    class Meta:
        db_table = 'res_dict'


class SuiteCount(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    group = models.CharField(max_length=32, null=True)
    suite = models.CharField(max_length=32, null=True)
    count = models.IntegerField(null=True)


class Node(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    ip_port = models.CharField(null=False, max_length=32)
    tag = models.CharField(max_length=64)
    status = models.CharField(max_length=16, default='on')

    def __str__(self):
        return self.ip_port


class RegisterFunction(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    group = models.CharField(max_length=32, null=True)
    suite = models.CharField(max_length=32, null=True)
    func = models.CharField(max_length=64, null=False)
    node = models.CharField(max_length=32, null=True)
    tests = models.CharField(max_length=512, null=True)


class Execution(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    func = models.ForeignKey(RegisterFunction, blank=False, null=False, on_delete=models.CASCADE, db_constraint=False)
    method = models.CharField(max_length=64)
    ds_range = models.CharField(max_length=32, null=True)
    comment = models.CharField(max_length=64, null=True)
    status = models.CharField(max_length=256, null=True)


class JobQueue(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    executioin = models.ForeignKey(Execution, on_delete=models.CASCADE, null=False, db_constraint=False)
    node = models.CharField(max_length=32, null=False)
    status = models.CharField(max_length=256, null=False)
    tester = models.CharField(max_length=32)
    create_time = models.DateTimeField(auto_created=True)
    update_time = models.DateTimeField(auto_created=False, null=True)


class DataSource(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    ds_name = models.CharField(max_length=64, null=False)
    file_name = models.CharField(max_length=128, null=False)
    file_path = models.FilePathField(path=settings.DATA_SOURCE_ROOT, max_length=256, null=False)
    update_time = models.DateTimeField(auto_created=False, null=True)

autotest/views.py
import base64
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView
from Utils.CustomView import ListViewWithMenu
from Utils.Paginator import *
from Utils.ReadExcel import *
from django.http import JsonResponse, HttpResponseRedirect, FileResponse
from .datasource import update_datasource
from .exec_test import *
from Utils.MyMixin import URIPermissionMixin
from Utils.decorators import auth_check, json_serializer
from .form import DataSourceForm
from .orm import *
from django.views.decorators.csrf import csrf_exempt
from SysAdmin.models import Sys_Config
from .serializers import UpdateRunhisCommentSerializer, ExecutionSerializer, RegsiterNodeSerializer, \
    UpdateSuiteCaseCountSerializer

PARENT_MENU = r'自动化测试\\(Code\\)'


class RunHisV(LoginRequiredMixin, URIPermissionMixin, ListViewWithMenu):
    template_name = 'autotest/run_his.html'
    context_object_name = 'options'
    parent_menu = PARENT_MENU

    def get_queryset(self, **kwargs):
        group = RunHis.objects.values('group').distinct()
        suite = RunHis.objects.values('suite').distinct()
        tester = RunHis.objects.values('tester').distinct()
        context = {
            'group': group,
            'suite': suite,
            'tester': tester
        }
        return context


@login_required
@auth_check
def get_run_his(request):
    # default get params: page=1 limit=10
    # {
    #     "code": 0,
    #     "msg": "",
    #     "count": "",
    #     "data": "[]"
    # }
    page = request.GET.get('page', '0')
    limit = request.GET.get('limit', '30')
    # expand = request.GET.get('expand', 'none')
    recent_90_days = datetime.datetime.strftime(datetime.datetime.now() + datetime.timedelta(days=-90), '%Y-%m-%d')
    run_his = filter_run_his(
        tester=request.GET.get('tester', None),
        group=request.GET.get('group', None),
        suite=request.GET.get('suite', None),
        testcase=request.GET.get('testcase', None),
        result=request.GET.get('result', None),
        beg=request.GET.get('beg', None) or recent_90_days,
        end=request.GET.get('end', None),
        order=True,
        eval_result=True
    ).values(
        'id', 'group', 'suite', 'case', 'title', 'tester', 'result', 'report', 'comment', 'create_time')
    count = len(run_his)
    data_list = paginator(run_his, int(page), int(limit))
    return JsonResponse({"code": 0, "msg": "", "count": count, "data": data_list})


@login_required
@auth_check
def get_report(request):
    runhis_id = request.GET.get('id', None)
    run_his = RunHis.objects.filter(id=runhis_id)
    if run_his:
        # HtmlTestReport: template loader模板渲染
        # run_his[0].report: test_group\test_suite\timestamp\xxxxx.html
        # template path 'test_group\test_suite\timestamp\xxxxx.html'
        if '.html' in run_his[0].report:
            return render(request, run_his[0].report.replace('\\', os.sep), {})
        # Pytest html report 静态文件服务
        # run_his[0].report: test_group\test_suite\timestamp\
        # 'ip:port/static/Report/test_group/test_suite/timestamp/index.html'
        else:
            report_dir = '/static/Report/'
            return HttpResponseRedirect(report_dir + run_his[0].report.replace('\\', '/') + '/index.html')
    else:
        report = '<h2>Can not get the report.</h2>'
        return render(request, 'autotest/report.html', {'report': report})


@login_required
@auth_check
@json_serializer(UpdateRunhisCommentSerializer)
def update_runhis_comment(request):
    # print(request.data)
    run_his = RunHis.objects.filter(group=request.data['group'], suite=request.data['suite'], case=request.data['case'],
                                    title=request.data['title'], report=request.data['report'],
                                    create_time=request.data['create_time'].replace('T', ' '))
    if run_his:
        run_his.update(comment=request.data['comment'])
        return JsonResponse({'msg': '备注更新成功!'}, json_dumps_params={'ensure_ascii': False})
    else:
        return JsonResponse({'msg': '测试历史记录不存在!'}, json_dumps_params={'ensure_ascii': False})


class ExecutionV(LoginRequiredMixin, URIPermissionMixin, ListViewWithMenu):
    template_name = 'autotest/execution.html'
    context_object_name = 'options'
    parent_menu = PARENT_MENU

    def get_queryset(self, **kwargs):
        nodes = Node.objects.filter(status='on')
        group = RegisterFunction.objects.values('group').distinct()
        suite = RegisterFunction.objects.values('suite').distinct()
        function = RegisterFunction.objects.values('func').distinct()
        csrf_token = self.request.COOKIES.get('csrftoken')
        context = {
            'nodes': nodes,
            'group': group,
            'suite': suite,
            'function': function,
            'csrf_token': csrf_token,
        }
        return context


@login_required
@auth_check
def get_jobs(request):
    page = request.GET.get('page', '0')
    limit = request.GET.get('limit', '30')
    jobs = filter_jobs(
        group=request.GET.get('group', None),
        suite=request.GET.get('suite', None),
        func=request.GET.get('func', None)
    )
    if len(jobs) > 0:
        data_list = paginator(jobs, int(page), int(limit))
    else:
        data_list = {}
    data_list = get_node_options(data_list)
    return JsonResponse({"code": 0, "msg": "", "count": len(jobs), "data": data_list})


@require_http_methods(['POST'])
@login_required
@auth_check
@json_serializer(ExecutionSerializer)
def exec_job(request):
    job_id = request.data['job_id']
    func = request.data['func'].strip()
    mthd = request.data['mthd'].strip()
    ds_range = request.data['ds_range'].strip()
    node = request.data['node'].strip()
    comment = request.data['comment'].strip()
    tester = request.session['user_name']
    res = execute_job_asyn(job_id, func, mthd, ds_range, node, comment, tester)
    return JsonResponse(res)


def execute_job_asyn(job_id, func, mthd, ds_range, node, comment, tester):
    """
       异步调用RPC执行测试用例的方法
    :param job_id: 任务主键id
    :param func: 对应用例组，测试类
    :param mthd: 对应测试方法
    :param ds_range: 参数范围
    :param node: 执行节点 ip:port
    :param comment: 备注
    :param tester: 测试人
    :return: json msg
    """
    # 校验是否存在
    exist_func = RegisterFunction.objects.filter(func=func, node=node)
    execution = Execution.objects.exclude(status='running').filter(id=job_id, func__func=func)
    execution_count = len(execution)
    free_node = Node.objects.filter(ip_port=node, status='on')
    if len(exist_func) > 0 and execution_count == 1 and len(free_node) > 0:
        # 更新关联关系
        execution.update(func=exist_func[0].id)
        # 占用节点
        for row in free_node:
            row.status = 'running'
            row.save()
        # 更新任务状态 任务不允许重复
        execution.update(status='running', method=mthd, ds_range=ds_range, comment=comment)
        # 多线程异步执行
        status = job_run(func, mthd, ds_range, node, comment, free_node, tester)
        # 线程异常，更新任务状态
        if 'Error' in status:
            execution.update(status=status)
        return {"msg": "提交成功!"}
    elif len(exist_func) > 0 and execution_count == 1:
        # 更新关联关系
        execution.update(func=exist_func[0].id)
        # 加入队列
        is_in_queue = len(JobQueue.objects.filter(executioin=execution[0], node=node, status='new'))
        if is_in_queue < 1:
            # 更新信息
            execution.update(status='in job queue', method=mthd, ds_range=ds_range, comment=comment)
            JobQueue(executioin=execution[0], node=node, status='new', tester=tester,
                     create_time=time.strftime('%Y-%m-%d %H:%M:%S', time.localtime())).save()
            return {"msg": "提交队列成功!"}
        else:
            return {"msg": "任务已在队列中!"}
    else:
        return {"msg": "ERROR: 节点注册方法或任务不存在，或执行节点不可用!"}


@login_required
@auth_check
def new_job_html(request):
    """
        新建任务的弹出层html
    """
    node_on = list(Node.objects.filter(status='on').values_list('ip_port', flat=True))
    func = RegisterFunction.objects.filter(node__in=node_on).distinct().values('group', 'suite', 'func',
                                                                               'tests', 'node').order_by('group',
                                                                                                         'suite',
                                                                                                         'node', 'func')
    # print(func)
    return render(request, 'autotest/new_job.html', {'func': func})


@require_http_methods(['POST'])
@login_required
@auth_check
@json_serializer(ExecutionSerializer)
def save_new_job(request):
    """
        保存新建任务
    """
    func = request.data['func'].strip()
    mthd = request.data['mthd'].strip()
    ds_range = request.data['ds_range'].strip()
    comment = request.data['comment'].strip()
    exec_count = len(Execution.objects.filter(func__func=func, method=mthd))
    get_func = RegisterFunction.objects.filter(func=func)
    if len(get_func) >= 1 and exec_count == 0:
        new = Execution(method=mthd, ds_range=ds_range, comment=comment, func=get_func[0])
        new.save()
        return JsonResponse({"msg": "保存成功!"})
    elif len(get_func) < 1:
        return JsonResponse({"msg": "ERROR: 节点注册方法不存在!"})
    elif exec_count > 0:
        return JsonResponse({"msg": "ERROR: 测试任务重复!"})
    else:
        return JsonResponse({"msg": "ERROR: 未知错误!"})


@require_http_methods(['POST'])
@login_required
@auth_check
@json_serializer(ExecutionSerializer)
def del_job(request):
    job_id = request.data['job_id']
    func = request.data['func'].strip()
    execution = Execution.objects.filter(id=job_id, func__func=func)
    if len(execution) > 0:
        if len(execution.filter(status='running')) > 0:

autotest/templates/autotest/datasource.html
{% extends "base.html" %}

{% block content %}
    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
        <legend>数据源管理</legend>
    </fieldset>
    <div class="layui-form layui-form-pane" lay-filter="search">
        {% csrf_token %}
        <div class="layui-form-item">
            <div class="search">
                <div class="layui-inline">
                    <label class="layui-form-label ">Ds_Name：</label>
                    <div class="layui-input-inline">
                        <input class="layui-input" name="ds_name" id="ds_name" autocomplete="off">
                    </div>
                    <button type="reset" class="layui-btn layui-inline" id="reset">重置</button>
                    <button class="layui-btn layui-inline" id="search" data-type="reload">搜索</button>
                </div>
            </div>
        </div>
    </div>
    <form id="download_form" action="{% url 'autotest:download_ds' %}" method="post">
        {% csrf_token %}
        <input class="ds_name" type="hidden" name="ds_name"/>
    </form>
    <table id="ds_table" lay-filter="ds_table">
        <input style="display: none" id="csrf" value={{ options.csrf_token }}>
    </table>
{% endblock %}

{% load static %}
{% block script %}
    <script type="text/html" id="actions">
        {% verbatim %}
        <a lay-event="preview_ds" class="layui-btn layui-btn-warm layui-btn-xs">查看</a>
        <a lay-event="get_ds" class="layui-btn layui-btn-xs">下载</a>
        <a lay-event="update_ds" class="layui-btn layui-btn-xs layui-btn-normal update_ds" id="{{ d.ds_name }}">上传更新</a>
        {% endverbatim %}
    </script>
    <script>
        !function () {
            let table = layui.table;
            let form = layui.form;
            let $ = layui.$;
            let upload = layui.upload;
            {#let expand = layui.sessionData('expand').expand;#}

            function renderUpload(upload) {
                {# 上传 #}
                let ds_name = '';
                upload.render({
                    elem: '.update_ds'
                    , url: '/autotest/datasource/update/'
                    , data: {
                        'ds_name': function () {
                            return ds_name;
                        }
                    }
                    , headers: {'X-CSRFToken': $("#csrf").val()}
                    , accept: 'file'
                    {#, acceptMime: 'application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/vnd.yaml'#}
                    , exts: 'xls|xlsx|yaml'
                    {# 单位KB #}
                    , size: 2048
                    , before: function (obj) {
                        let thisRow = this.item;
                        ds_name = thisRow.attr('id');
                        layer.load(1);
                    }
                    , done: function (res) {
                        console.log(res);
                        layer.open({
                            content: '<div style="padding: 20px 100px;">' + res.msg + '</div>'
                            , type: 1
                            , title: '提示'
                            , time: 5000
                            , btn: '确定'
                            , yes: function () {
                                layer.closeAll();
                            }
                        });
                    }
                });
            }

            let ds_name = $('#ds_name').val();
            let ds_table = table.render({
                elem: '#ds_table'
                , height: 'full'
                , url: '/autotest/datasource/get/'
                , where: {
                    ds_name: ds_name
                }
                , page: {
                    curr: 1,
                    limit: 10
                }
                , even: true
                , cols: [[
                    {
                        field: 'no', title: 'No', sort: false, align: 'center', templet(d) {
                            return d.LAY_NUM;
                        }
                    }
                    , {field: 'ds_name', title: 'Datasource Name', sort: false, align: 'center'}
                    , {
                        field: 'update_time', title: 'Update Time', sort: true, align: 'center', templet(d) {
                            return d.update_time.replace('T', ' ');
                        }
                    }
                    , {
                        field: 'actions', title: 'Actions', align: 'center', toolbar: '#actions'
                    }
                ]]
                , done: function (res, curr, count) {
                    {# 上传 #}
                    renderUpload(upload);
                }
            });

            table.on('tool(ds_table)', function (obj) {
                {#获得当前行数据#}
                let data = obj.data;
                {#获得 lay-event 对应的值#}
                let layEvent = obj.event;
                {#当前行tr的DOM对象#}
                let tr = obj.tr;
                const nodes_csrf = $("#csrf").val();
                if (layEvent === 'get_ds') {
                    {#下载数据源#}
                    {#ajax无法下载#}
                    let form = $("#download_form");
                    form.children("input.ds_name").attr('value', data.ds_name);
                    form.submit();
                    {#node_table.reload();#}
                } else if (layEvent === 'preview_ds') {
                    {#console.log(data.ds_name)#}
                    let url = "/autotest/datasource/preview/"
                    let title = '数据源预览: ' + data.ds_name
                    $.ajax({
                        url: url
                        , type: "GET"
                        , data: {ds_name: data.ds_name}
                        , success: function (data) {
                            {#console.log(data);#}
                            layer.open({
                                content: data
                                , type: 1
                                , title: title
                                , area: '1200px'
                                , btn: '关闭'
                                , yes: function () {
                                    layer.closeAll();
                                }
                            });
                        }
                    });
                }
            });

            let active = {
                reload: function () {
                    {#let expand = layui.sessionData('expand').expand;#}
                    let ds_name = $('#ds_name').val();
                    {#console.log(group);#}
                    ds_table.reload({
                        page: {
                            curr: 1
                        }
                        , where: {
                            ds_name: ds_name
                        }
                        , done: function (res, curr, count) {
                            {# 上传 #}
                            renderUpload(upload);
                        }
                    });
                }
            };

            $('#search').on('click', function () {
                let type = $(this).data('type');
                active[type] ? active[type].call(this) : '';
            });

            $('#reset').on('click', function () {
                form.val('search', {
                    "ds_name": ''
                });
            });
        }();
    </script>
{% endblock %}

autotest/templates/autotest/datasource_preview.html
{% if data.excel %}
    <div class="layui-tab">
    <ul class="layui-tab-title">
        {% for title in data.sheetnames %}
            {% if forloop.first %}
                <li class="layui-this">{{ title }}</li>
            {% else %}
                <li>{{ title }}</li>
            {% endif %}
        {% endfor %}
        {#            <li class="layui-this">网站设置</li>#}
    </ul>
    <div class="layui-tab-content">
        {% for k, v in data.excel.items %}
            {% if forloop.counter == 1 %}
                <div class="layui-tab-item layui-show">
            {% else %}
                <div class="layui-tab-item">
            {% endif %}
            <table lay-filter="{{ k }}">
                <thead>
                <tr>
                    {% for col in v.1 %}
                        <th lay-data="{field:'a_{{ forloop.counter }}'}">{{ forloop.counter }}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody>
                {% for row in v %}
                    <tr>
                        {% for col in row %}
                            <td>{{ col }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% endfor %}
        {#            <div class="layui-tab-item layui-show">内容1</div>#}
        </div>
    </div>
{% endif %}
{% if data.yaml %}
    <pre class="layui-code">
        {{ data.yaml }}
    </pre>
{% endif %}

{% load static %}
<script>
    !function () {
        layui.use('element', function () {
            let element = layui.element;
        });
        let table = layui.table;
        {% if data.excel %}
            {% for title in data.sheetnames %}
                table.init('{{title}}', {
                    even: true
                });
            {% endfor %}
        {% endif %}
        {% if data.yaml %}
            layui.use('code', function () {
                layui.code();
            });
        {% endif %}
    }();
</script>

autotest/templates/autotest/new_job.html
<div class="layui-form  layui-form-pane" lay-filter="new_job" style="padding: 20px 5em;">
    {% csrf_token %}
    <div class="new_job"  style="min-width: 70%">
        <div class="layui-form-item">
            <label class="layui-form-label" style="min-width: 40%"><span style="color: red">*</span>RPC
                Function：</label>
            <div class="layui-input-inline">
                <select name="new_func" id="new_func" lay-verify="required" lay-filter="new_func">
                    <option value="">请选择注册测试类</option>
                </select>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label" style="min-width: 40%">Method：</label>
            <div class="layui-input-inline">
{#                <input class="layui-input" name="new_method" id="new_method" autocomplete="off">#}
                <select name="new_method" id="new_method" lay-verify="required" lay-filter="new_method">
                    <option value="">请选择测试方法</option>
                </select>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label" style="min-width: 40%">Range：</label>
            <div class="layui-input-inline">
                <input class="layui-input" name="new_ds_range" id="new_ds_range" autocomplete="off">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label" style="min-width: 40%">Comment：</label>
            <div class="layui-input-inline">
                <input class="layui-input" name="new_comment" id="new_comment" autocomplete="off">
            </div>
        </div>
    </div>
</div>
<script>
    {#弹出层需要重新渲染#}
    layui.use('form', function () {
        let fm = layui.form;
        let funcs = [];
        {% if func %}
            let methods, methods_opt;
            {% for opt in func %}
                methods = '{{opt.tests}}';
                methods_opt = methods.split(',');
                funcs.push({'func': '{{ opt.func }}', 'group': '{{ opt.group }}', 'suite': '{{ opt.suite }}', 'methods':methods_opt});
                $('#new_func').append($('<option value="{{ opt.func }}"></option>').text('{{ opt.group }} - {{ opt.suite }}: {{ opt.func }}({{ opt.node }})'));
            {% endfor %}
        {% endif %}
        fm.render(null, 'new_job');

        fm.on('select(new_func)', function (data) {
            let selected_func = data.value;
            let new_method =  $("#new_method");
            $("#new_method option").remove();
            new_method.append($('<option value="">请选择测试方法</option>')).append($('<option value="all">all</option>'));
            for(let i in funcs){
                if(selected_func && selected_func === funcs[i]['func']){
                    let mthds = funcs[i]['methods'];
                    for (let j in mthds) {
                        new_method.append($('<option value="' + mthds[j] + '"></option>').text(mthds[j]));
                    }
                    break;
                }
            }
            fm.render(new_method);
        });

    });
</script>

autotest/templates/autotest/report.html
<html>
    <body>
        <iframe width="100%" height="100%">
            {{ report }}
        </iframe>
    </body>
</html>