MyWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from MyWeb import settings
from MyWeb.APScheduler import start_scheduler

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('login/', include('login.urls')),
    path('autotest/', include('autotest.urls', namespace='autotest')),
    path('sysadmin/', include('SysAdmin.urls', namespace='sysadmin')),
    path('apitest/', include('ApiTest.urls', namespace='apitest')),
    path('datapanel/', include('DataPanel.urls', namespace='datapanel')),
]

# 随项目启动运行
if settings.APSCHEDULER == 'on':
    start_scheduler()

login/urls.py
from django.urls import path
from . import views

app_name = 'login'
# handler403 = views.permission_denied

urlpatterns = [
    path('', views.LoginV.as_view(), name='login'),
    path('index/', views.IndexV.as_view(), name='index'),
    path('logout/', views.logout_v, name='logout'),
    path('403/', views.permission_denied, name='permission_denied'),
    path('personal/', views.PersonalInfoV.as_view(), name='personal'),
]

MyWeb/templates/Untitled-1.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>layout 后台大布局 - Layui</title>
  <link rel="stylesheet" href="../src/css/layui.css">
</head>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
  <div class="layui-header">
    <div class="layui-logo">layui 后台布局</div>
    <!-- 头部区域（可配合layui已有的水平导航） -->
    <ul class="layui-nav layui-layout-left">
      <li class="layui-nav-item"><a href="">控制台</a></li>
      <li class="layui-nav-item"><a href="">商品管理</a></li>
      <li class="layui-nav-item"><a href="">用户</a></li>
      <li class="layui-nav-item">
        <a href="javascript:;">其它系统</a>
        <dl class="layui-nav-child">
          <dd><a href="">邮件管理</a></dd>
          <dd><a href="">消息管理</a></dd>
          <dd><a href="">授权管理</a></dd>
        </dl>
      </li>
    </ul>
    <ul class="layui-nav layui-layout-right">
      <li class="layui-nav-item">
        <a href="javascript:;">
          <img src="http://t.cn/RCzsdCq" class="layui-nav-img">
          贤心
        </a>
        <dl class="layui-nav-child">
          <dd><a href="">基本资料</a></dd>
          <dd><a href="">安全设置</a></dd>
        </dl>
      </li>
      <li class="layui-nav-item"><a href="">退了</a></li>
    </ul>
  </div>
  
  <div class="layui-side layui-bg-black">
    <div class="layui-side-scroll">
      <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
      <ul class="layui-nav layui-nav-tree"  lay-filter="test">
        <li class="layui-nav-item layui-nav-itemed">
          <a class="" href="javascript:;">所有商品</a>
          <dl class="layui-nav-child">
            <dd><a href="javascript:;">列表一</a></dd>
            <dd><a href="javascript:;">列表二</a></dd>
            <dd><a href="javascript:;">列表三</a></dd>
            <dd><a href="">超链接</a></dd>
          </dl>
        </li>
        <li class="layui-nav-item">
          <a href="javascript:;">解决方案</a>
          <dl class="layui-nav-child">
            <dd><a href="javascript:;">列表一</a></dd>
            <dd><a href="javascript:;">列表二</a></dd>
            <dd><a href="">超链接</a></dd>
          </dl>
        </li>
        <li class="layui-nav-item"><a href="">云市场</a></li>
        <li class="layui-nav-item"><a href="">发布商品</a></li>
      </ul>
    </div>
  </div>
  
  <div class="layui-body">
    <!-- 内容主体区域 -->
    <div style="padding: 15px;">内容主体区域</div>
  </div>
  
  <div class="layui-footer">
    <!-- 底部固定区域 -->
    © layui.com - 底部固定区域
  </div>
</div>
<script src="../src/layui.js"></script>
<script>
//JavaScript代码区域
layui.use('element', function(){
  let element = layui.element;
  
});
</script>
</body>
</html>

MyWeb/templates/base.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
    {% load static %}
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href=" {% static 'css/layui.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href=" {% static 'iconfont.css' %}">
    <link rel="stylesheet" href=" {% static 'weathericon.css' %} ">
    <script src="{% static 'Constants.js' %}"></script>
    {% block statics %}
    {% endblock %}
    <style>
        .layui-nav {
            border-radius: 0;
        }
        .layui-nav-tree .layui-nav-more {
            right: 10px;
        }
        .layui-nav-tree .layui-nav-item>a {
            padding-left: 10px;
        }
    </style>
</head>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <!--head nav-->
    <div class="layui-header">
        <div class="layui-logo"><a href="" style="color: #009680; font-size: 17px"> Automated Test Platform</a></div>
        <!-- header-nav -->
        <ul class="layui-nav layui-layout-left">
            {% block head_nav %}
            {% endblock %}
        </ul>
        <ul class="layui-nav layui-layout-right">
            <li class="layui-nav-item">
                <a href="javascript:;">
                    <i class="layui-icon layui-icon-username" style="font-size: 18px;"></i>
                    {{ user_name }} - {{ user_group }}
                </a>
                <dl class="layui-nav-child">
                    <dd><a href="{% url 'login:personal' %}"><i class="layui-icon layui-icon-about"
                                                                style="font-size: 16px;"></i> 个人中心</a></dd>
                    <dd><a href="{% url 'login:logout' %}"><i class="layui-icon layui-icon-logout"
                                                              style="font-size: 16px;"></i> 注销</a></dd>
                </dl>
            </li>
            <li class="layui-nav-item"><a href=""> </a></li>
        </ul>
    </div>

    <!--left-nav-tree-->
    {% if menus %}
        <div class="layui-side layui-bg-cyan">
            <div class="layui-side-scroll">
                <ul class="layui-nav layui-nav-tree layui-bg-cyan" lay-shrink="all" lay-filter="test">
                    <li class="layui-nav-item">
                        <a class="首页" href="{% url 'login:index' %}">
                            <i class="layui-icon layui-icon-home" style="font-size: 18px;"></i>
                            首页
                        </a>
                    </li>
                    {% for first_level in menus %}
                        {#                        <li class="layui-nav-item {% ifequal first_level.text '自动化测试' %}layui-nav-itemed{% endifequal %}">#}
                        <li class="layui-nav-item">
                            <a class="{{ first_level.text }}" href="{{ first_level.url }}">
                                {% if first_level.icon %}
                                    <i class="layui-icon {{ first_level.icon }}"
                                       style="font-size: 18px;"></i>
                                {% endif %}
                                {{ first_level.text }}
                            </a>
                            {% if first_level.childs %}
                                <dl class="layui-nav-child">
                                    {% for child in first_level.childs %}
                                        <dd><a href="{{ child.url }}">
                                            {% if child.icon %}
                                                <i class="layui-icon {{ child.icon }}"
                                                   style="font-size: 18px;"></i>
                                            {% endif %}
                                            {{ child.text }}
                                        </a></dd>
                                    {% endfor %}
                                </dl>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endif %}


    {#<!-- body -->#}
    {# 修改原始样式,不出现滚动条,和footer配合 #}
    <div class="layui-body" style="bottom: 20px;">
        {% block content %}
        {% endblock %}
    </div>
    <!-- footer -->
    <div class="layui-footer" style="max-height: 20px;line-height:20px">
        © ted.wang
    </div>

</div>
{% load static %}
<script src="{% static 'layui.js' %} "></script>
<script>
    {#!function () {#}
    layui.config({
        base: '/static/ext/',
        version: 'v1.8.0'
    }).extend({
        soulTable: 'soulTable',
    });
    var layer = layui.layer;
    var $ = layui.jquery;
    var element = layui.element;
    $(".layui-side li.layui-nav-item a").on('click', function () {
        let expand = $(this).attr('class');
        if (layui.sessionData('expand').expand === 'none' || layui.sessionData('expand').expand !== expand) {
            {#console.log('expand');#}
            layui.sessionData('expand', {key: 'expand', value: expand});
        } else {
            {#console.log('remove');#}
            layui.sessionData('expand', {key: 'expand', value: 'none'});
        }
    });

    var exp = layui.sessionData('expand').expand;
    {% if expand %}
        if (layui.sessionData('expand').expand === 'none' || layui.sessionData('expand').expand == null) {
            exp = "{{expand}}";
            layui.sessionData('expand', {key: 'expand', value: exp});
        }
    {% endif %}
    if (exp != null && exp.toString() !== '') {
        $("." + exp).parent().attr("class", "layui-nav-item layui-nav-itemed");
    }
    {% if message %}
        layer.open({
            content: '<div style="padding: 20px 100px;">' + '{{message}}' + '</div>'
            , type: 1
            , title: '提示'
            , time: 5000
            , btn: '确定'
            , yes: function () {
                layer.closeAll();
            }
        });
    {% endif %}
    {# }();#}
</script>
{% load static %}
{% block script %}
{% endblock %}
</body>
</html>